apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-proxy-configmap
  labels:
    kiamol: ch09
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      proxy_cache_path /data/nginx/cache levels=1:2 keys_zone=STATIC:1m inactive=24h  max_size=1g;

      gzip  on;    
      gzip_proxied any;

      map $sent_http_content_type $expires {
        default                    off;
        ~image/                    6M;
      } 

      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
            proxy_pass             http://todo-web;
            proxy_set_header       Host $host;
            proxy_cache            STATIC;
            proxy_cache_valid      200  10s;
            proxy_cache_use_stale  error timeout invalid_header updating
                                   http_500 http_502 http_503 http_504;
            add_header             X-Cache     $upstream_cache_status;
            add_header             X-Host      $hostname;         
        }
      }
    }
