apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vweb
  labels:
    kiamol: ch15
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: vweb.kiamol.local
    http:
      paths:
      - path: /
        backend:
          service:
            name: vweb-v2
            port:
              number: 80
      - path: /v1
        backend:
          service:
            name: vweb-v1
            port:
              number: 80
      - path: /v2
        backend:
          service:
            name: vweb-v2
            port:
              number: 80
