apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo2-new
  labels:
    kiamol: ch15
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: Path
    traefik.ingress.kubernetes.io/router.tls: "true"    
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
  - host: todo2.kiamol.local
    http:
      paths:
      - path: /new
        backend:
          service:
            name: todo-web-sticky
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo2-static
  labels:
    kiamol: ch15
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    traefik.ingress.kubernetes.io/router.tls: "true"    
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
  - host: todo2.kiamol.local
    http:
      paths:
      - path: /static
        backend:
          service:
            name: todo-web
            port: 
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo2
  labels:
    kiamol: ch15
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.pathmatcher: Path
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
  - host: todo2.kiamol.local
    http:
      paths:
      - path: /
        backend:
          service:
            name: todo-web
            port: 
              number: 80
      - path: /list
        backend:
          service:
            name: todo-web
            port: 
              number: 80
