apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}  
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: bulletin-board
    app.kubernetes.io/instance: {{ .Release.Name }}
    kiamol: ch11-lab
spec:
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http
  selector:
    app.kubernetes.io/name: bulletin-board
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.serviceType }}