version: "3.7"

services:
  ch02-hello-kiamol:
    image: kiamol/ch02-hello-kiamol:latest
    build:
      context: ./hello-kiamol

  ch02-whoami:
    image: kiamol/ch02-whoami:latest
    build:
      context: ./whoami
